/* eslint-disable import/no-default-export */

import { type Metadata } from 'next'

import dynamic from 'next/dynamic'
import { cookies } from 'next/headers'

import logger from 'loglevel'

import { createAxiosBaseQuery } from '@boilerplate/core/builders/axios-base-query.builder'
import { type HttpClientResponse, Method } from '@boilerplate/core/interfaces/http'
import { Role } from '@boilerplate/core/interfaces/user'

import { GetProfileMyUrl } from '@boilerplate/types/auth/dto/requests/profile'
import { type MyProfile } from '@boilerplate/types/auth/interfaces/profile'

import { ReduxProvider } from '@boilerplate/front-end/store/provider'

import { Footer } from '@boilerplate/front-end/components/footer'
import { Header } from '@boilerplate/front-end/components/header'
import { Progress } from '@boilerplate/front-end/components/progress'
import { Snackbar } from '@boilerplate/front-end/components/snackbar'

import '@boilerplate/dashboard/assets/css/satoshi.css'
import '@boilerplate/dashboard/assets/css/style.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import '@boilerplate/front-end/app/global.scss'

export interface RootLayoutProps {
  readonly children: React.ReactNode
}

const ConfirmDeletion = dynamic(() => import('@boilerplate/front-end/components/confirms/delete'))
const ConfirmChanges = dynamic(() => import('@boilerplate/front-end/components/confirms/changes'))

export const metadata: Metadata = {
  title: 'Figure shop',
  description: 'Generated by create next app',
}

const RootLayout: React.FC<RootLayoutProps> = async ({ children }) => {
  const cookieStore = cookies()

  const { value: token } = cookieStore.get('jwt') || {}

  let profile: MyProfile | null = null

  if (token) {
    try {
      const request = createAxiosBaseQuery()

      const response = (await request({
        method: Method.Get,
        url: GetProfileMyUrl,
        params: {
          role: Role.User,
        },
        headers: {
          Authorization: `Bearer ${token}`,
        },
      })) as HttpClientResponse<MyProfile>

      if (response.error) {
        throw new Error(response.error)
      }

      profile = response.data
    } catch (error) {
      logger.error(error)
    }
  }

  return (
    <html lang="en" style={{ fontFamily: 'Arial, sans-serif' }}>
      <head>
        <meta name="format-detection" content="telephone=no, date=no, email=no, address=no" />
      </head>
      <body>
        <ReduxProvider profile={profile}>
          <Progress />
          <Header />
          {children}
          <Footer />
          <Snackbar />
          <ConfirmDeletion />
          <ConfirmChanges />
        </ReduxProvider>
      </body>
    </html>
  )
}

logger.setLevel('debug')

export default RootLayout
